#include "SecOC_Cfg.h"

uint8 TX_APDU_Buffer[SECOC_NUM_OF_TX_IPDU*64];
uint8 TX_SPDU_Buffer[TX_SINGLE_IPDU*64];
uint8 TX_ALPDU_Buffer[TX_COLLECTION_IPDU*64];
uint8 TX_CPDU_Buffer[TX_COLLECTION_IPDU*64];
